### PR TITLE
Utils: Recent versions of json-c return the size as a size_t

### PR DESCRIPTION
**Pull request by rgacogne**

### CODE REVIEW

**Comment by rgacogne** [comment]
@gdelafond Any idea why it looks like a GET HTTP request to http://www.aquaray.fr/ yielded a 403? Shall we use a different target instead?

**Comment by gdelafond** [comment]
@rgacogne no idea, it should work (at least get a 301 Moved Permanently). The website maybe was broken at the time you tested it ?

**Comment by gdelafond** [comment]
The MR looks good for me.

**Review by gdelafond — APPROVED** [review]
It looks good for me.

**Pull request merged**
